"""add new column

Revision ID: 3a7bd733cb68
Revises: d87381f25d58
Create Date: 2026-08-05 14:42:13.170334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7bd733cb68'
down_revision: Union[str, Sequence[str], None] = 'd87381f25d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mistakes_id'))

    op.drop_table('user_mistakes')
    op.drop_table('words')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwordClear', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('passwordClear')

    op.create_table('words',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('word', sa.TEXT(), nullable=False),
    sa.Column('translation', sa.TEXT(), nullable=False),
    sa.Column('transcription', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mistakes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('word_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_mistakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_mistakes_id'), ['id'], unique=False)

    # ### end Alembic commands ###
