"""create all tables

Revision ID: 6b8a2ec474aa
Revises: 464e793b5823
Create Date: 2026-08-08 20:10:41.159165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8a2ec474aa'
down_revision: Union[str, Sequence[str], None] = '464e793b5823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_word'), ['word'], unique=False)

    op.create_table('user_mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_mistakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_mistakes_id'), ['id'], unique=False)

    op.create_table('user_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('is_learned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_results_id'))

    op.drop_table('user_results')
    with op.batch_alter_table('user_mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mistakes_id'))

    op.drop_table('user_mistakes')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word'))
        batch_op.drop_index(batch_op.f('ix_words_id'))

    op.drop_table('words')
    # ### end Alembic commands ###
